language: node_js
node_js:
  - 10
before_script:
  - npm install @11ty/eleventy -g
script: eleventy
deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
